Chronister/ChronalRobot

modules/handmade.py
Updated q&a bot command to better address the duplicate question issue.
=> Updated 'q&a' 

modules/handmade_faq.py
!math command explains the usefulness of mathematics in game programming. !wheel answers the question of "Why reinvent the wheel?" as it pertains to Handmade Hero. !cleancode explains why at times we prefer not to follow "Clean Code" principles at all.
=> Added new bot commands

modules/handmade_faq.py
Also using goog.gl for consistency.
=> Significantly shortened some functions.

modules/handmade_faq.py
Removed a link, substituted another.
=> Changes to 'cleancode' bot command.

modules/handmade_stream.py
Some fixes for a couple issues and one I happened across while working on the others.
=> Fix some issues related to the handmade_stream module.

modules/caseyquotes.py
Fixes Chronister/ChronalRobot#30
Fixes Chronister/ChronalRobot#31
Adds getting a specfic quote
Adds quote# when stating quotes
=> Add quote management

modules/handmade_faq.py
Some people have wanted to use !patreon instead of !buy, so I made a new alias.
=> Added 'patreon' alias for 'buy' command.

modules/handmade_faq.py
One for showing the software used on stream, and another for the Jeff and Casey show link.
=> Added new commands.

modules/handmade_faq.py
Used to show the platforms Handmade Hero will be ported to aside from its original Windows implementation.
=> Added a port command

modules/handmade_faq.py
New !engine alias for !lib command.
=> Added alias for lib. Can now use engine as a bot command.

modules/handmade_faq.py
New command with aliases to explain Casey's handwriting.
=> Added new command for tablet info.

modules/caseyquotes.py
Added command aliases "edit" and "editQuote" for ChronalDragon :)
=> Added fixquote aliases

modules/handmade.py
Added command to see who the owner of the bot is. Command (currently) is whitelisted and shown only in !listmore
=> Added !owner command

modules/handmade.py
Switched whitelisted to whitelisted_streamtime
=> Changed !owner user group

modules/handmade_stream.py
=> fixed off day streams from showing up as scheduled

modules/caseyquotes.py
This should probably be changed to query the db using a regex of searchString to eliminate the forloop, but my knowledge of SQLobject is too limited to properly form such a statement
=> Added in the ability to search for quotes based on a string.

modules/handmade_faq.py, sql/duplicateQuoteCheck.sql
.sql file can be manually run (for example, in SQLiteBrowser) to check for duplicate quotes. Might expand on it in the future, but it's simple for now.
=> Added source tweet to !break and included a .sql file

modules/handmade_faq.py
Added a link to video series for math programmers for the command !math
=> Added a link to video series for math programmers for the command !math

modules/handmade_faq.py
Figured SSL would be a good idea since I offer the .db to be downloaded, and had to change the subdomain for Cloudflare support to work for that server. Required a new shortURL, thus this pull request exists.
=> Updated !quotelist link for SSL support

modules/handmade_faq.py
And expanded !build with a link to Day 11 video explaining it.
=> !unity and !stu aliases added to !build

modules/handmade_faq.py
Was cut off on Twitch and Slack IRC alike. Down to 362 chars.
=> [v2] Shortened !build

modules/handmade.py
See commit message 4aca43b for details.
=> findquote system change

modules/handmade_faq.py
Essentially copy of !msdn, accepts !search, !s, !g, and !google
=> Added Google search

README.md, Setup.md, sampleconfig.txt, sql/duplicateQuoteCheck.sql
A while ago when it was requested we re-add the config to the repository, it was also requested that we explain how to get it working. I decided to be nice and documented everything that needs to be checked and changed before the bot will work properly.
If I can think of anything else that might cause a hiccup in the bot, I'll try to document it in [Setup.md](https://github.com/Chronister/ChronalRobot/blob/master/Setup.md)
=> Added documentation, corrected spelling

modules/handmade_faq.py
We need some good resources to give to:
1) absolute beginners looking to dip their toes in programming and maybe not ready to commit to complicated environment setups
2) people with some exposure to coding who want to get into lower level stuff like on stream, but aren't good enough to follow along yet
Serviced by !learning and !learnC, respectively.
The changes in my pull request are somewhat better than the current versions of the commands, but I don't think they're quite perfect yet. Looking for suggestions for other websites/resources to put in them.
=> Updates to the !learning commands

modules/handmade_faq.py
Reverts Chronister/ChronalRobot#80
=> Revert "Updates to the !learning commands"

modules/handmade_faq.py
Short summary of date, location and ticket prices for HandmadeCon 2015,
with link to handmadecon.org for further info.
=> !hmhcon, !con, !convention added

modules/handmade_bonus.py
!blame -> hmh_bot blames Satya Nadella.
!blame for that -> hmh_bot blames Satya Nadella for that.
!blame because of reason -> hmh_bot blames Satya Nadella because of reason.
=> Update blame per d7's suggestion.

modules/handmade_faq.py
with OpenGL, which will need to be updated if/when he changes what he is
doing.
=> Added !opengl command to further specifiy what Casey is actually doing
